CREATE DATABASE IF NOT EXISTS form;

CREATE USER 'dev'@'localhost' IDENTIFIED BY 'pwd';
GRANT ALL PRIVILEGES ON form.* TO 'dev'@'localhost';
FLUSH PRIVILEGES;

USE form;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
